### ISSUE TITLE
Alternative equivalents for split, symmetry and f_equal?

### ISSUE THREAD

**Issue by jaens** [katydid/coq-lean-cheatsheet#1]
A person [on Twitter writes](https://twitter.com/Someody42/status/1685340978721206272):

> [@Someody42](https://twitter.com/Someody42)
> The right equivalent for split, symmetry and f_equal are constructor, symm and congr (although the last one is a bit annoying sometimes so congrArg is good to know)

Not sure if relevant, just reposting here in case it could be useful.

**Comment by awalterschulze** [comment]
Thank you, I replied on twitter :)
